'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinREG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CleyNextTheSeaChurch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CleyNextTheSeaChurch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duplicate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duplicate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception when opening existing file.
        '''</summary>
        Friend ReadOnly Property err0001() As String
            Get
                Return ResourceManager.GetString("err0001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transcription file not found.
        '''</summary>
        Friend ReadOnly Property err0002() As String
            Get
                Return ResourceManager.GetString("err0002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header {0} is not correct according to the FreeREG specifications:-{1}{2}{1}{1}{3}.
        '''</summary>
        Friend ReadOnly Property err0003() As String
            Get
                Return ResourceManager.GetString("err0003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Burial Age is badly formatted.
        '''</summary>
        Friend ReadOnly Property err0004() As String
            Get
                Return ResourceManager.GetString("err0004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Age of the Bride is invalid. The accepted format is: [number][d|w|m], [number]y[number][d|w|m], minor, of age, full age or of full age..
        '''</summary>
        Friend ReadOnly Property err0005() As String
            Get
                Return ResourceManager.GetString("err0005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Age of the Groom is invalid. The accepted format is: [number][d|w|m], [number]y[number][d|w|m], minor, of age, full age or of full age..
        '''</summary>
        Friend ReadOnly Property err0006() As String
            Get
                Return ResourceManager.GetString("err0006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Place Name field must be at least 3 characters in length..
        '''</summary>
        Friend ReadOnly Property err0007() As String
            Get
                Return ResourceManager.GetString("err0007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select one of the available record types..
        '''</summary>
        Friend ReadOnly Property err0008() As String
            Get
                Return ResourceManager.GetString("err0008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select one of the available counties..
        '''</summary>
        Friend ReadOnly Property err0009() As String
            Get
                Return ResourceManager.GetString("err0009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The WinREG Tables file can not be found. A re-installation of the product is recommended..
        '''</summary>
        Friend ReadOnly Property err0010() As String
            Get
                Return ResourceManager.GetString("err0010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered date is badly formatted.
        '''</summary>
        Friend ReadOnly Property err0011() As String
            Get
                Return ResourceManager.GetString("err0011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered month name is invalid.
        '''</summary>
        Friend ReadOnly Property err0012() As String
            Get
                Return ResourceManager.GetString("err0012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid month name abbreviation.
        '''</summary>
        Friend ReadOnly Property err0013() As String
            Get
                Return ResourceManager.GetString("err0013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A non-numeric month name must be 3 or more characters in length.
        '''</summary>
        Friend ReadOnly Property err0014() As String
            Get
                Return ResourceManager.GetString("err0014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In September 1752, the 3rd through to 13th inclusive were omitted from the calendar.
        '''</summary>
        Friend ReadOnly Property err0015() As String
            Get
                Return ResourceManager.GetString("err0015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month is invalid when used in double-dating. Only Jan, Feb and Mar are allowed..
        '''</summary>
        Friend ReadOnly Property err0016() As String
            Get
                Return ResourceManager.GetString("err0016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to March 25th and after can not be double-dated.
        '''</summary>
        Friend ReadOnly Property err0017() As String
            Get
                Return ResourceManager.GetString("err0017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn of century should be expressed with 00.
        '''</summary>
        Friend ReadOnly Property err0018() As String
            Get
                Return ResourceManager.GetString("err0018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The double-year entry is invalid. The second part should be one greater than the first part..
        '''</summary>
        Friend ReadOnly Property err0019() As String
            Get
                Return ResourceManager.GetString("err0019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double-year can not be greater than 99.
        '''</summary>
        Friend ReadOnly Property err0020() As String
            Get
                Return ResourceManager.GetString("err0020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double-year must be numeric.
        '''</summary>
        Friend ReadOnly Property err0021() As String
            Get
                Return ResourceManager.GetString("err0021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year must be numeric.
        '''</summary>
        Friend ReadOnly Property err0022() As String
            Get
                Return ResourceManager.GetString("err0022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This date should be double-dated.
        '''</summary>
        Friend ReadOnly Property err0023() As String
            Get
                Return ResourceManager.GetString("err0023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day number should be numeric.
        '''</summary>
        Friend ReadOnly Property err0024() As String
            Get
                Return ResourceManager.GetString("err0024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After 1751, double-dating does not apply.
        '''</summary>
        Friend ReadOnly Property err0025() As String
            Get
                Return ResourceManager.GetString("err0025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year was not a leap-year.
        '''</summary>
        Friend ReadOnly Property err0026() As String
            Get
                Return ResourceManager.GetString("err0026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Century was not a leap-year.
        '''</summary>
        Friend ReadOnly Property err0027() As String
            Get
                Return ResourceManager.GetString("err0027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The updater program, &apos;{0}&apos; is not present. Automatic program updates will not be available..
        '''</summary>
        Friend ReadOnly Property err0028() As String
            Get
                Return ResourceManager.GetString("err0028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The updater configuration file, &apos;{0}&apos; can not be found. Automatic program updates will not be available..
        '''</summary>
        Friend ReadOnly Property err0029() As String
            Get
                Return ResourceManager.GetString("err0029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In order to validate the contents of a file, you must have opened it in the first place.
        '''</summary>
        Friend ReadOnly Property err0030() As String
            Get
                Return ResourceManager.GetString("err0030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The data grid is not sortable by the &apos;{0}&apos; column.
        '''</summary>
        Friend ReadOnly Property err0031() As String
            Get
                Return ResourceManager.GetString("err0031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oops! Don&apos;t know how to sort the &apos;{0}&apos; column..
        '''</summary>
        Friend ReadOnly Property err0032() As String
            Get
                Return ResourceManager.GetString("err0032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only alphabetic and numeric characters are allowed in this part of the filename.
        '''</summary>
        Friend ReadOnly Property err0033() As String
            Get
                Return ResourceManager.GetString("err0033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must complete the entry of your User Details before you can proceed any further.
        '''</summary>
        Friend ReadOnly Property err0034() As String
            Get
                Return ResourceManager.GetString("err0034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Excel spreadsheet file contains more than one sheet. The program is currently unable to handle a multi-sheet file. Select another file or alter the file so that it only has a single sheet in it..
        '''</summary>
        Friend ReadOnly Property err0035() As String
            Get
                Return ResourceManager.GetString("err0035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The last, empty line is reserved for adding a new record, it can not be deleted..
        '''</summary>
        Friend ReadOnly Property err0036() As String
            Get
                Return ResourceManager.GetString("err0036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following is a list of dates that are somewhat problematical when it comes to sorting them:-.
        '''</summary>
        Friend ReadOnly Property err0037() As String
            Get
                Return ResourceManager.GetString("err0037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please correct these dates if you can. If not, email these dates to the development team..
        '''</summary>
        Friend ReadOnly Property err0038() As String
            Get
                Return ResourceManager.GetString("err0038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If separator characters (/- .) are used within a date, then they must be used consistently. They can not be mixed..
        '''</summary>
        Friend ReadOnly Property err0039() As String
            Get
                Return ResourceManager.GetString("err0039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter 3 characters to complete this part of the file name.
        '''</summary>
        Friend ReadOnly Property err0040() As String
            Get
                Return ResourceManager.GetString("err0040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Age at Burial is over 100 years and is thus suspect.
        '''</summary>
        Friend ReadOnly Property err0041() As String
            Get
                Return ResourceManager.GetString("err0041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text must consist of letters, numbers, spaces and the following punctuation: ?!:;.,+=*.
        '''</summary>
        Friend ReadOnly Property err0042() As String
            Get
                Return ResourceManager.GetString("err0042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your file ({0}) has been successfully renamed internally to {1}. To make the change of name permanent, you must save the file..
        '''</summary>
        Friend ReadOnly Property err0043() As String
            Get
                Return ResourceManager.GetString("err0043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Updater has encountered the error &apos;{0}&apos;. Please notify the developers..
        '''</summary>
        Friend ReadOnly Property err0044() As String
            Get
                Return ResourceManager.GetString("err0044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Place Code field must be 3 characters in length..
        '''</summary>
        Friend ReadOnly Property err0045() As String
            Get
                Return ResourceManager.GetString("err0045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WinREG can only read or write comma separated files that have an extension of .CSV. .
        '''</summary>
        Friend ReadOnly Property err0046() As String
            Get
                Return ResourceManager.GetString("err0046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WinREG can only read spreadsheet files that have an extension of .XLS or .XSLX..
        '''</summary>
        Friend ReadOnly Property err0047() As String
            Get
                Return ResourceManager.GetString("err0047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All files that can be opened by WinREG must have names that conform to the standard of &lt;county&gt;&lt;place&gt;&lt;type&gt;[suffix]. {0}.
        '''</summary>
        Friend ReadOnly Property err0048() As String
            Get
                Return ResourceManager.GetString("err0048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Baptism is before the Date of Birth.
        '''</summary>
        Friend ReadOnly Property err0049() As String
            Get
                Return ResourceManager.GetString("err0049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to locate the .ERR file {0}. Button will henceforth be disabled for this transcription file..
        '''</summary>
        Friend ReadOnly Property err0050() As String
            Get
                Return ResourceManager.GetString("err0050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header record {0} is missing.
        '''</summary>
        Friend ReadOnly Property err0051() As String
            Get
                Return ResourceManager.GetString("err0051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File header records are present and correct, but there is no data in the file.
        '''</summary>
        Friend ReadOnly Property err0052() As String
            Get
                Return ResourceManager.GetString("err0052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to County code on first data record ({0}) doesn&apos;t match the Chapman code of the County name in the second header record ({1}).
        '''</summary>
        Friend ReadOnly Property err0053() As String
            Get
                Return ResourceManager.GetString("err0053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data record 1 does not start with a valid Chapman Code.
        '''</summary>
        Friend ReadOnly Property err0054() As String
            Get
                Return ResourceManager.GetString("err0054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Problem clearing clipboard contents. Message is {0}. There is no need to worry, the problem is probably insignificant..
        '''</summary>
        Friend ReadOnly Property err0055() As String
            Get
                Return ResourceManager.GetString("err0055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to County name in header record 2 has been corrected from {0} to {1}.
        '''</summary>
        Friend ReadOnly Property err0056() As String
            Get
                Return ResourceManager.GetString("err0056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line {0} is badly formed and can not be recognised as a valid CSV record. The file is most likely corrupt.
        '''</summary>
        Friend ReadOnly Property err0057() As String
            Get
                Return ResourceManager.GetString("err0057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Brides Age at marriage is over 100!.
        '''</summary>
        Friend ReadOnly Property err0058() As String
            Get
                Return ResourceManager.GetString("err0058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Grooms Age at marriage is over 100!.
        '''</summary>
        Friend ReadOnly Property err0059() As String
            Get
                Return ResourceManager.GetString("err0059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The support to import spreadsheet files is not present on your PC..
        '''</summary>
        Friend ReadOnly Property err0060() As String
            Get
                Return ResourceManager.GetString("err0060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have the necessary support to import spreadsheet files with an extension of XLSX.
        '''</summary>
        Friend ReadOnly Property err0061() As String
            Get
                Return ResourceManager.GetString("err0061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The record contains errors that may prevent the successful upload of the data. You can either save the data with the errors, go back and correct the errors, or discard whatever changes you have made to the record..
        '''</summary>
        Friend ReadOnly Property err0062() As String
            Get
                Return ResourceManager.GetString("err0062", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Exclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There were {0} badly formatted records in the {1} file. Please consult the Log File (see the Help menu) for a list of the errors. Do you want to correct these errors now?.
        '''</summary>
        Friend ReadOnly Property infBadlyFormattedRecords() As String
            Get
                Return ResourceManager.GetString("infBadlyFormattedRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The contents of the Register Number field ({1}) in record {0} is not numeric. FreeREG will not accept this. Clear the field? Alternatively, press Cancel to abort the File Open operation..
        '''</summary>
        Friend ReadOnly Property infBadRegisterNumber() As String
            Get
                Return ResourceManager.GetString("infBadRegisterNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking {0} for residual errors....
        '''</summary>
        Friend ReadOnly Property infCheckingFile() As String
            Get
                Return ResourceManager.GetString("infCheckingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importing {0} ....
        '''</summary>
        Friend ReadOnly Property infImportingFile() As String
            Get
                Return ResourceManager.GetString("infImportingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is your last chance to save the data. Save it or lose it!.
        '''</summary>
        Friend ReadOnly Property infLastChance() As String
            Get
                Return ResourceManager.GetString("infLastChance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading the file data into the table ....
        '''</summary>
        Friend ReadOnly Property infLoadData() As String
            Get
                Return ResourceManager.GetString("infLoadData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading {0} .....
        '''</summary>
        Friend ReadOnly Property infLoadingFile() As String
            Get
                Return ResourceManager.GetString("infLoadingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The LookUp Tables have been recreated. All previous user additions and changes have been lost..
        '''</summary>
        Friend ReadOnly Property infLookUpTablesCreated() As String
            Get
                Return ResourceManager.GetString("infLookUpTablesCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first data field MUST be +INFO. The second data field is the e-mail address of the submitter. The third data field is a password that may be required in the future; at the present time simply use password for this field. The fourth data field is the nature of the data records. For FreeREG this must be SEQUENCED. The Fifth data field is the type of register information being submitted. It can be one of BAPTISMS, MARRIAGES, BURIALS.The sixth data field identifies the character set used in the file. If you [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property infRecord1() As String
            Get
                Return ResourceManager.GetString("infRecord1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first data field must be #. The second data field should be CCC. The third data field is the submitter&apos;s name. The fourth data field is the group with which the submitter is working. The fifth data field is the file name of the transcribed file. The file name must consist of: [three letter Chapman code for the county][a three letter placename code assigned by the person uploading the file][BA|BU|MA][part number, if any].CSV. The file name should be all upper case. ( The sixth data field contains the dat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property infRecord2() As String
            Get
                Return ResourceManager.GetString("infRecord2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first data field must be #. The second data field should be CREDIT. The third data field is the submitter&apos;s name.The fourth data field is the submitter&apos;s e-mail address..
        '''</summary>
        Friend ReadOnly Property infRecord3() As String
            Get
                Return ResourceManager.GetString("infRecord3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first data field must be #. The second data field should be the date the file was modified. The third and any other data fields are any comments the submitter wishes to make about the file..
        '''</summary>
        Friend ReadOnly Property infRecord4() As String
            Get
                Return ResourceManager.GetString("infRecord4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file that you are attempting to {0}, contains residual data errors that will prevent the file from being accepted by the FreeREG website. Do you want to continue?.
        '''</summary>
        Friend ReadOnly Property infResidualErrors() As String
            Get
                Return ResourceManager.GetString("infResidualErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving {0} ....
        '''</summary>
        Friend ReadOnly Property infSavingFile() As String
            Get
                Return ResourceManager.GetString("infSavingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Updater has detrmined that there are new software updates available. Do you want to download and install these changes now?.
        '''</summary>
        Friend ReadOnly Property infUpdatesAvailable() As String
            Get
                Return ResourceManager.GetString("infUpdatesAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program is already registered as a default program for opening CSV files. Do you want to remove this association?.
        '''</summary>
        Friend ReadOnly Property msgAlreadyDefaultProgram() As String
            Get
                Return ResourceManager.GetString("msgAlreadyDefaultProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program is registered as a Default Program. Would you like to make the program a default program for opening CSV files?.
        '''</summary>
        Friend ReadOnly Property msgAssociateWithCsvFiles() As String
            Get
                Return ResourceManager.GetString("msgAssociateWithCsvFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As well as removing the entry from the AutoCompletion list, you can also clear those entries from the existing records. Do you want to clear all occurences of &quot;{0}&quot; from their {1}?.
        '''</summary>
        Friend ReadOnly Property msgClearTableEntries() As String
            Get
                Return ResourceManager.GetString("msgClearTableEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are dropping the file {0} onto the grid, do you want to replace the current file with the alternative one?.
        '''</summary>
        Friend ReadOnly Property msgCloseAndOpenDroppedFile() As String
            Get
                Return ResourceManager.GetString("msgCloseAndOpenDroppedFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you really sure that you want to shut the program down?.
        '''</summary>
        Friend ReadOnly Property msgConfirmExit() As String
            Get
                Return ResourceManager.GetString("msgConfirmExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to copy record {0} and create a new record?.
        '''</summary>
        Friend ReadOnly Property msgCopyRecord() As String
            Get
                Return ResourceManager.GetString("msgCopyRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected directory doesn&apos;t exist. Do you want to create it?.
        '''</summary>
        Friend ReadOnly Property msgCreateDirectory() As String
            Get
                Return ResourceManager.GetString("msgCreateDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have pressed the button that causes the removal of a row from the table. Are you sure that you want to delete this row?.
        '''</summary>
        Friend ReadOnly Property msgDeleteRow() As String
            Get
                Return ResourceManager.GetString("msgDeleteRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are trying to delete one of the fixed, permanent records of this table. This is simply not possible..
        '''</summary>
        Friend ReadOnly Property msgDeletingTableRecord() As String
            Get
                Return ResourceManager.GetString("msgDeletingTableRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program has come across some corruptions to the first four fields in one or more records of the file. Where possible, these corruptions have been corrected. Please see the Message Log for details of what has been found and corrected..
        '''</summary>
        Friend ReadOnly Property msgFileCorrupted() As String
            Get
                Return ResourceManager.GetString("msgFileCorrupted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program is unable to create a JumpList. Please enable &apos;Recent Documents Tracking&apos; if you wish to use this feature. See Windows Help for more information..
        '''</summary>
        Friend ReadOnly Property msgJumpListDisabled() As String
            Get
                Return ResourceManager.GetString("msgJumpListDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file ({0}) no longer exists in its&apos; original position. Do you want to remove the reference from the MRUlist?.
        '''</summary>
        Friend ReadOnly Property msgMRUFileMissing() As String
            Get
                Return ResourceManager.GetString("msgMRUFileMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This person being married or buried is 100 years old or older. Is this correct?.
        '''</summary>
        Friend ReadOnly Property msgOldperson() As String
            Get
                Return ResourceManager.GetString("msgOldperson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are dropping the file {0}, do you want to open it?.
        '''</summary>
        Friend ReadOnly Property msgOpenDroppedFile() As String
            Get
                Return ResourceManager.GetString("msgOpenDroppedFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have made changes to the file that have not yet been saved to disk. Do you want to save the changes now? {0}.
        '''</summary>
        Friend ReadOnly Property msgSaveFile() As String
            Get
                Return ResourceManager.GetString("msgSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred. Do you want the program to send a screenshot and other information about the error to the Developers?.
        '''</summary>
        Friend ReadOnly Property msgUnexpectedError() As String
            Get
                Return ResourceManager.GetString("msgUnexpectedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file {0} {1}, has Username [{2}] and EmailAddress [{3}] that differ from your current settings. Do you want to update the file to match your settings?.
        '''</summary>
        Friend ReadOnly Property msgUpdateHeader() As String
            Get
                Return ResourceManager.GetString("msgUpdateHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As well as changing the entry in the AutoCompletion list, you can also update those same entries within the existing records. Do you want to change all occurences of &quot;{0}&quot; to &quot;{1}&quot;?.
        '''</summary>
        Friend ReadOnly Property msgUpdateTableEntries() As String
            Get
                Return ResourceManager.GetString("msgUpdateTableEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to winreg.tables.
        '''</summary>
        Friend ReadOnly Property nameTablesFile() As String
            Get
                Return ResourceManager.GetString("nameTablesFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to winreg.user.tables.
        '''</summary>
        Friend ReadOnly Property nameUserTablesFile() As String
            Get
                Return ResourceManager.GetString("nameUserTablesFile", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property QuestionMark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionMark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;Day&gt;(?&lt;Missing&gt;\*)|(?&lt;UnreadableCharacter&gt;_[0-9])|(?&lt;UnreadableCharacter&gt;[0-3]_)|(?&lt;DayTens&gt;0[1-9])|(?&lt;DayTwenties&gt;[1-2][0-9])|(?&lt;DayThirties&gt;3[0-1])|(?&lt;SingleDigit&gt;[1-9]))$.
        '''</summary>
        Friend ReadOnly Property rgxDay() As String
            Get
                Return ResourceManager.GetString("rgxDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3} \.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?).
        '''</summary>
        Friend ReadOnly Property rgxEmailAddress() As String
            Get
                Return ResourceManager.GetString("rgxEmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (?&lt;year&gt;(?&lt;num1&gt;\d{1,3})(?&lt;unit1&gt;y)(?&lt;num2&gt;\d{1,3})(?&lt;unit2&gt;[dmw])).
        '''</summary>
        Friend ReadOnly Property rgxMarriageAgeComplex() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAgeComplex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (?&lt;year&gt;(?&lt;number&gt;\d{1,3})(?&lt;unit&gt;[dmw]?)).
        '''</summary>
        Friend ReadOnly Property rgxMarriageAgeSimple() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAgeSimple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;Month&gt;\*|(?&lt;Capital&gt;J|j)an|(?&lt;Capital&gt;F|f)eb|(?&lt;Capital&gt;M|m)ar|(?&lt;Capital&gt;A|a)pr|(?&lt;Capital&gt;M|m)ay|(?&lt;Capital&gt;J|j)un|(?&lt;Capital&gt;J|j)ul|(?&lt;Capital&gt;A|a)ug|(?&lt;Capital&gt;S|s)ep|(?&lt;Capital&gt;O|o)ct|(?&lt;Capital&gt;N|n)ov|(?&lt;Capital&gt;D|d)ec)$.
        '''</summary>
        Friend ReadOnly Property rgxMonth() As String
            Get
                Return ResourceManager.GetString("rgxMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?ni:(((((?&lt;days&gt;(31(?&lt;suffix&gt;st)?(?!(\ ((?:F|f)eb(ruary)?|(?:A|a)pr(il)?|(?:J|j)une?|((?:S|s)ep(?=\b|t)t?|(?:N|n)ov)(ember)?))|[ -/.]{0,2}(0?[2469]|11)))|((30|29)(?&lt;suffix&gt;th)?(?!((\ (?:F|f)eb(ruary)?)|([ -/.]{0,2}0?2))))|(29(?&lt;suffix&gt;th)?(?=(([ -/.]{0,2}(?:F|f)eb(ruary)?[ -/.]{0,2})|([ -/.]{0,2}0?2[ -/.]{0,2}))(((1[5-9]|[2-9]\d)(0[48]|[2468][048]|[13579][26])|((16|[2468][048]|[3579][26])00)))))|(?&lt;suffix&gt;(?=\d\d?[nrst][dht]\ [JFMASOND])(\b2?(1st|2nd|3rd|[4-8]th)|20th|1\dth\b)|((0?[1-9])|1\d|2[0-8]))|\*|[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property rgxValidateDate() As String
            Get
                Return ResourceManager.GetString("rgxValidateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?ni:(((((?&lt;days&gt;(31(?&lt;suffix&gt;st)?(?!(\ ((?:F|f)eb(ruary)?|(?:A|a)pr(il)?|(?:J|j)une?|((?:S|s)ept?|(?:N|n)ov)(ember)?))|[-/ .]{0,2}(0?[2469]|11)))|((30|29)(?&lt;suffix&gt;th)?(?!((\ (?:F|f)eb(ruary)?)|([-/ .]{0,2}0?2))))|(29(?&lt;suffix&gt;th)?(?=(([ -/.]{0,2}(?:F|f)eb(ruary)?[ -/.]{0,2})|([ -/.]{0,2}0?2))))|(?&lt;suffix&gt;(?=\d\d?[nrst][dht]\ [JFMASOND])(\b2?(1st|2nd|3rd|[4-8]th)|20th|1\dth\b)|((0?[1-9])|1\d|2[0-8]))|\*|[0123]_|_\d)(?&lt;sep1&gt;[-/ .]*)?(?&lt;month&gt;((?&lt;monthnumber&gt;1[012]|0?[1-9]))|((?&lt;monthname&gt;(\*|(?:J|j)an(uary [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property rgxValidateDoubleDate() As String
            Get
                Return ResourceManager.GetString("rgxValidateDoubleDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;Year&gt;\*|(?:_|1|2)(?:_|[5-9]|0)(?:_|[0-9])(?:_|[0-9]))$.
        '''</summary>
        Friend ReadOnly Property rgxYear() As String
            Get
                Return ResourceManager.GetString("rgxYear", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
